version: '3.8'

services:
  nginx:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "81:80"
    depends_on:
      - api-server
    networks:
      - incident-report-app-network

  api-server:
    build:
      context: ./server
    depends_on:
      postgresql-db:
        condition: service_healthy
    networks:
      - incident-report-app-network

  postgresql-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: incident-report
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - incident-report-app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:

networks:
  incident-report-app-network:
    driver: bridge
